import type { KnipConfig } from 'knip';

const config: KnipConfig = {
    entry: [
        'src/index.ts',           // MCP server entry
        'src/cli/index.ts',       // CLI bin entry
        'src/metrics-server.ts',  // Standalone metrics server
        'scripts/**/*.{ts,mjs}',  // Build-time scripts
    ],
    project: [
        'src/**/*.ts',
        'scripts/**/*.{ts,mjs}',
        // Include tests so devDeps used only in tests (e.g. testcontainers in keycloak-container.ts)
        // are not reported as unused.
        'tests/**/*.ts',
    ],
    ignore: [
        'dist/**',
        'src/embed-docs/**',      // Generated at build time
        // Generated by scripts/embed-docs.ts. Getters (getTemplates, getTools, getMem, getTemplate,
        // listResourceKeys) are part of the MCP resource API and may be used by MCP clients or
        // tooling; they are not imported in src, so knip reports them as unused.
        'src/resources/embedded-mcp-resources.ts',
    ],
    ignoreDependencies: [
        // Runtime tools used in scripts/shell, not imported directly
        'dotenv-cli',
        'pino-pretty',
        'concurrently',
    ],
    // Knip reports "Unlisted binaries: python3" because it's referenced in package.json scripts
    // but not declared as a dependency. It's a system binary used by infra:up for Keycloak
    // realm setup (scripts/configure-keycloak-realms.py).
    ignoreBinaries: ['python3'],
    ignoreExportsUsedInFile: true,
};

export default config;
