apiVersion: v1
kind: Namespace
metadata:
  name: kairos-operators
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: kairos-operators
  namespace: kairos-operators
spec:
  targetNamespaces:
    - kairos
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: keycloak-operator
  namespace: kairos-operators
spec:
  channel: fast
  installPlanApproval: Automatic
  name: keycloak-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: percona-postgresql-operator
  namespace: kairos-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: percona-postgresql-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: kairos-catalog
  namespace: olm
spec:
  displayName: kairos-catalog
  image: ghcr.io/debian777/kairos-olm-catalog:latest
  publisher: kairos-mcp
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: spotahome-redis-operator
  namespace: kairos-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: spotahome-redis-operator
  source: kairos-catalog
  sourceNamespace: olm
