apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - gatewayclass-ngrok.yaml
  - catalogsource-ngrok.yaml
  - operatorgroup.yaml
  - subscription-ngrok-operator.yaml
