apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ngrok-operator
  namespace: ngrok-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: ngrok-operator
  source: ngrok-catalog
  sourceNamespace: olm
