{{- $gateway := default dict .Values.gateway }}
{{- $tls := default dict $gateway.tls }}
{{- $certManager := default dict $tls.certManager }}
{{- if and $gateway.enabled $certManager.enabled $gateway.hostname }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-gateway-tls
  labels:
    app.kubernetes.io/part-of: {{ .Chart.Name | quote }}
spec:
  secretName: {{ $certManager.secretName | default (printf "%s-gateway-tls" .Release.Name) }}
  issuerRef:
    {{- toYaml $certManager.issuerRef | nindent 4 }}
  dnsNames:
    - {{ $gateway.hostname }}
{{- end }}
