{{- if and .Values.keycloakDcrCleanup.enabled .Values.keycloakInstance.enabled (not .Values.keycloakInstance.useOwnCluster) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-dcr-cleanup
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Chart.Name | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-dcr-cleanup
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Chart.Name | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-dcr-cleanup
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Chart.Name | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-dcr-cleanup
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-dcr-cleanup
    namespace: {{ .Release.Namespace }}
{{- end }}
