{{- if and .Values.keycloakDcrCleanup.enabled .Values.keycloakInstance.enabled (not .Values.keycloakInstance.useOwnCluster) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-dcr-cleanup-state
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Chart.Name | quote }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
data:
  seen_clients: "{}"
{{- end }}
