{{- if and .Values.keycloakRealmImport.enabled .Values.keycloakInstance.enabled (not .Values.keycloakInstance.useOwnCluster) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-realm-imported
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Chart.Name | quote }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
data: {}
{{- end }}
