{{- if and .Values.keycloakDcrCleanup.enabled .Values.keycloakInstance.enabled (not .Values.keycloakInstance.useOwnCluster) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-dcr-cleanup-script
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Chart.Name | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
data:
  cleanup.py: |
{{ .Files.Get "files/keycloak-dcr-cleanup.py" | indent 4 }}
{{- end }}
