{{- if and .Values.postgresCluster.enabled .Values.postgresCluster.vpa.enabled .Values.postgresCluster.vpa.targetName }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Chart.Name | quote }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: {{ .Values.postgresCluster.vpa.targetKind | default "StatefulSet" }}
    name: {{ .Values.postgresCluster.vpa.targetName }}
  updatePolicy:
    updateMode: {{ .Values.postgresCluster.vpa.updateMode }}
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        minAllowed:
          memory: {{ .Values.postgresCluster.vpa.minAllowed.memory }}
          cpu: {{ .Values.postgresCluster.vpa.minAllowed.cpu }}
        maxAllowed:
          memory: {{ .Values.postgresCluster.vpa.maxAllowed.memory }}
          cpu: {{ .Values.postgresCluster.vpa.maxAllowed.cpu }}
{{- end }}
