{{- if and .Values.redisCluster.enabled (not .Values.redisCluster.useOwnCluster) }}
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: {{ .Values.redisCluster.name }}
  namespace: {{ .Values.redisCluster.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Chart.Name | quote }}
spec:
  {{- with .Values.redisCluster.customSpec }}
  {{- toYaml . | nindent 2 }}
  {{- else }}
  sentinel:
    replicas: {{ .Values.redisCluster.sentinelReplicas }}
  redis:
    replicas: {{ .Values.redisCluster.replicas }}
  {{- end }}
{{- end }}
