#!/usr/bin/env bash
# Generate random secrets for Keycloak dev profile and write them to .env.
# Passwords are generated on this machine and never echoed; the AI/code never sees them.
#
# Usage:
#   ./scripts/generate-dev-secrets.sh
#
# To reinit Keycloak with fresh DB and new passwords:
#   docker compose --profile infra down -v
#   rm -rf ./data/keycloak_pgdata
#   ./scripts/generate-dev-secrets.sh
#   docker compose --profile infra up -d

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"

# Generate a random password (24 bytes, base64)
gen_pass() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 24
  else
    head -c 24 /dev/urandom | base64
  fi
}

KEYCLOAK_ADMIN_PASSWORD="$(gen_pass)"
KEYCLOAK_DB_PASSWORD="$(gen_pass)"

# Preserve VOLUME_LOCAL_PATH if .env already exists
VOLUME_LOCAL_PATH="./data"
if [ -f "$ENV_FILE" ]; then
  existing=$(grep -E '^VOLUME_LOCAL_PATH=' "$ENV_FILE" 2>/dev/null | cut -d= -f2-)
  if [ -n "$existing" ]; then
    VOLUME_LOCAL_PATH="$existing"
  fi
fi

# Write .env (overwrites existing secret vars, keeps others if we ever add more)
{
  echo "# Generated by scripts/generate-dev-secrets.sh - do not commit"
  echo "VOLUME_LOCAL_PATH=$VOLUME_LOCAL_PATH"
  echo "KEYCLOAK_ADMIN_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD"
  echo "KEYCLOAK_DB_PASSWORD=$KEYCLOAK_DB_PASSWORD"
} > "$ENV_FILE"

echo "Created .env with random Keycloak admin and DB passwords (secrets not shown)."
echo "To reinit Keycloak: docker compose --profile infra down -v && rm -rf ./data/keycloak_pgdata && ./scripts/generate-dev-secrets.sh && docker compose --profile infra up -d"
