import { buildForwardWidgetHtml } from '../../src/mcp-apps/forward-widget-html.js';

describe('buildForwardWidgetHtml', () => {
  test('includes MCP Apps handshake and forward tool-result handling', () => {
    const html = buildForwardWidgetHtml();
    expect(html).toContain('ui/initialize');
    expect(html).toContain('ui/notifications/initialized');
    expect(html).toContain('ui/notifications/tool-result');
    expect(html).toContain('isForwardStructured');
    expect(html).toContain('kairos-forward-view');
    expect(html).toContain('ui/notifications/host-context-changed');
    expect(html).toContain('paintHostContext');
    expect(html).toContain('data-theme');
    expect(html).toContain('html.dark');
    expect(html).toContain("classList.add('dark')");
    expect(html).toContain('id="header-title"');
    expect(html).toContain('id="progress-segments"');
    expect(html).toContain('id="step-text"');
    expect(html).not.toContain('status-pill');
    expect(html).toContain('formatStepTitle');
    expect(html).toContain('Retrying step:');
    expect(html).toContain('step-retrying');
    expect(html).toContain('isRewardNext');
    expect(html).toContain('All steps complete');
    expect(html).toContain('step-reward-ready');
    expect(html).toContain('footer-step-done');
    expect(html).not.toContain('step-reward-hint');
    expect(html).not.toContain('Call reward to finalize this adapter run');
    expect(html).toContain('renderProgress');
    expect(html).toContain('seg-issue');
    expect(html).toContain('--color-warning');
    expect(html).toContain('kairos-forward-root');
    expect(html).toContain('normalizeForwardErrorState');
    expect(html).toContain('renderForwardError');
    expect(html).toContain('renderHumanError');
    expect(html).toContain('Fix tool input and retry');
    expect(html).toContain('shortHumanErrorMessage');
    expect(html).toContain('Your AI agent was asked to: ');
    expect(html).toContain('Technical details');
    expect(html).toContain('notifySize');
    expect(html).not.toContain('<!DOCTYPE html>');
  });
});
