name: Publish npm Package

on:
  workflow_dispatch:
    inputs:
      force:
        description: 'Force publish (e.g. republish same version)'
        required: false
        default: false
        type: boolean

jobs:
  publish:
    uses: ./.github/workflows/reusable-publish-npm.yml
    with:
      sync-version-from-ref: false
      allow-existing-version: false
      force-publish: ${{ github.event.inputs.force == 'true' }}
      upload-sbom: false
    secrets: inherit
